name: logging_to_logcat_example
description: Demonstrates how to use the logging_to_logcat plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.1
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  logcat_monitor : ^0.0.6 # Abandonware, incompatible with AGP 8
  logging: ^1.2.0

  logging_to_logcat:
    # When depending on this package from a real application you should use:
    #   logging_to_logcat: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true